apiVersion: v1
kind: Service
metadata:
  name: hostservice-srv
spec:
  selector:
    app: hostservice    #deploy 의 Pod 이름
  ports:
  - port: 80          #업스트림 포트 지금 정함
    targetPort: 8080  #다운스트림 포트 deploy 파일에서 8080으로 정해놓음
