apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostservice-deploy
spec:
  selector:
    matchLabels:
      app: hostservice  #이거랑
  
  template:
    metadata:
      labels:
        app: hostservice  #이거랑 같아야함
    
    spec:
      containers:
      - name: hostservice-cont
  
        images: phl0904/node-app:35a646377bfcc613a23163450b7d3258a1fab9bc
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
